AWSTemplateFormatVersion: "2010-09-09"

Description: example-prod-foobar

#======================
# パラメーター
#======================

Parameters:

# プロジェクト名を入力する。
  EnvironmentName:
    Type: String
    Default: example-prod

# サービス名を入力する。
  ServiceName:
    Type: String
    Default: foobar

# VPCのCIDRレンジ
  VpcCIDR:
    Type: String
    Default: 172.31.0.0/16

# パブリックサブネット1
  PublicSubnet1CIDR:
    Type: String
    Default: 172.31.0.0/20

# パブリックサブネット2
  PublicSubnet2CIDR:
    Type: String
    Default: 172.31.16.0/20

# プライベートサブネット1
  PrivateSubnet1CIDR:
    Type: String
    Default: 172.31.48.0/20

# プライベートサブネット2
  PrivateSubnet2CIDR:
    Type: String
    Default: 172.31.64.0/20

# ドメイン名を入力する
  DomainName:
    Type: String
    Default: nakama-ec-api.click

#サービスが実行するタスクの数を指定する
  DesiredCount:
    Type: String
    Default: 1

#======================
# リソース
#======================

Resources:

#======================
##### ACM #####
#======================

# 証明書作成
  Root:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-nakama-ec-api-click

#======================
##### Route53 #####
#======================

# 検証用のALIASレコード作成
  Route53:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !Sub ${ApplicationLoadBalancer.DNSName}
        EvaluateTargetHealth: true
        HostedZoneId: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
      HostedZoneId: Z06376351PERTY5W4JDAZ
      Name: !Ref DomainName
      Type: A

#======================
#####  IAM #####
#======================

# タスク実行ロール作成
  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-${ServiceName}-ecs-task-execution
      AssumeRolePolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "ecs-tasks.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-${ServiceName}-ecs-task-execution

# タスクロール作成
  EcsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-${ServiceName}-ecs-task
      AssumeRolePolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "ecs-tasks.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-${ServiceName}-ecs-task

# タスク実行ポリシー作成
  EcsTaskExecutionPolicy:
    Type: AWS::IAM::Policy
    DependsOn: EcsTaskExecutionRole
    Properties:
      PolicyName: !Sub ${EnvironmentName}-${ServiceName}-ecs-task-execution
      Roles:
        - !Ref EcsTaskExecutionRole
      PolicyDocument:
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "ecr:GetAuthorizationToken",
                "ecr:BatchCheckLayerAvailability",
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchGetImage",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
              ],
              Resource: "*"
            }
          ]
        }

# パラメータ参照ポリシー作成
  ssmPolicy:
    Type: AWS::IAM::Policy
    DependsOn: EcsTaskExecutionRole
    Properties:
      PolicyName: !Sub ${EnvironmentName}-${ServiceName}-ssm
      Roles:
        - !Ref EcsTaskExecutionRole
      PolicyDocument:
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "ssm:GetParameters",
                "ssm:GetParameter",
              ],
              Resource: "*"
            }
          ]
        }

# タスクポリシー作成
  EcsTaskSsmPolicy:
    Type: AWS::IAM::Policy
    DependsOn: EcsTaskRole
    Properties:
      PolicyName: ssm
      Roles:
        - !Ref EcsTaskRole
      PolicyDocument:
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "ssmmessages:CreateControlChannel",
                "ssmmessages:CreateDataChannel",
                "ssmmessages:OpenControlChannel",
                "ssmmessages:OpenDataChannel",
              ],
              Resource: "*"
            }
          ]
        }

# #======================
# #####  ECR #####
# #======================

# nginx用のECR作成
  NginxRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${EnvironmentName}-${ServiceName}-nginx
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Hold only 10 images, expire all others",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-${ServiceName}-nginx

# php用のECR作成
  PhpRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${EnvironmentName}-${ServiceName}-php
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Hold only 10 images, expire all others",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-${ServiceName}-php

#======================
##### VPC #####
#======================

# VPC作成
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-main

# インターネットゲートウェイ作成
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-main

# インターネットゲートウェイをVPCにアタッチする
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

# パブリックサブネット1を作成
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-main-public-1

# パブリックサブネット2を作成
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-main-public-2

# プライベートサブネット1を作成
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-main-private-1

# プライベートサブネット2を作成
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnet2CIDR
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-main-private-2

# ルートテーブル（パブリックサブネット用共通）作成
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-main-public

# ルートテーブル（パブリックサブネット用共通）にインターネットゲートウェイへのルートを作成
  InternetGatewayPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable

# ルートテーブル（パブリックサブネット用共通）とパブリックサブネット1を紐付ける
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

# ルートテーブル（パブリックサブネット用共通）とパブリックサブネット2を紐付ける
  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2

# NATGatewayをパブリックサブネットに作成
  NatGateway1:
    Type: AWS::EC2::NatGateway
    DependsOn: NATGatewayEIP1
    Properties:
      AllocationId:
        Fn::GetAtt:
        - NATGatewayEIP1
        - AllocationId
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-main-1

# NATGateway用のElasticIPを作成
  NATGatewayEIP1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-nat-gateway-1

# ルートテーブル（プライベートサブネット用共通）作成
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-main-private-1

# ルートテーブル（プライベートサブネット用共通）にNATGatewayへのルートを作成
  NATGatewayPrivateRoute:
    Type: AWS::EC2::Route
    DependsOn: NatGateway1
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway1
      RouteTableId: !Ref PrivateRouteTable

# ルートテーブル（プライベートサブネット用共通）とプライベートサブネット1を紐付ける
  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet1

# ルートテーブル（プライベートサブネット用共通）とプライベートサブネット2を紐付ける
  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet2

# セキュリティグループ（Web）
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-main-web
      GroupDescription: WebSecurityGroup
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - FromPort: 80
          ToPort: 80
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
        - FromPort: 443
          ToPort: 443
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - FromPort: 0
          ToPort: 0
          IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-main-web

# セキュリティグループ（VPC）
  VpcSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-main-vpc
      GroupDescription: VpcSecurityGroup
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - FromPort: 0
          ToPort: 0
          IpProtocol: -1
          CidrIp: !Ref VpcCIDR
      SecurityGroupEgress:
        - FromPort: 0
          ToPort: 0
          IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-main-vpc

#======================
##### ALB #####
#======================

# ALB作成
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${EnvironmentName}-nakama-ec-api-click
      Scheme: internet-facing
      SecurityGroups:
        - !Ref WebSecurityGroup
        - !Ref VpcSecurityGroup
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      Type: application
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-nakama-ec-api-click

# ALBのリスナー作成(HTTPS)
  ApplicationLoadBalancerHttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: !Ref Root
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ApplicationServiceTargetGroup

# ALBのリスナー作成(HTTP)
  ApplicationLoadBalancerHttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Port: 443
            Protocol: HTTPS
            StatusCode: HTTP_301

# ターゲットグループ作成
  ApplicationServiceTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-foobar
      Port: 80
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VPC
      HealthyThresholdCount: 2
      HealthCheckIntervalSeconds: 30
      Matcher:
        HttpCode: 200
      HealthCheckPath: /
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      UnhealthyThresholdCount: 2
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-foobar

#======================
##### ECS作成 #####
#======================

# ECSCluster作成
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${EnvironmentName}-${ServiceName}
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-${ServiceName}

# タスク定義作成
  ApplicationTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${EnvironmentName}-${ServiceName}
      TaskRoleArn: !Ref EcsTaskRole
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref EcsTaskExecutionRole
      Memory: 512
      Cpu: 256
      Volumes:
        - Name: php-fpm-socket
      ContainerDefinitions:
        - Name: nginx
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EnvironmentName}-${ServiceName}-nginx:latest
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
          DependsOn:
            - ContainerName: php
              Condition: START
          MountPoints:
            - ContainerPath: /var/run/php-fpm
              SourceVolume: php-fpm-socket
        - Name: php
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EnvironmentName}-${ServiceName}-php:latest
          Secrets:
            - Name: APP_KEY
              ValueFrom: /example/prod/foobar/APP_KEY
          MountPoints:
            - ContainerPath: /var/run/php-fpm
              SourceVolume: php-fpm-socket
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-${ServiceName}

# サービス作成
  ApplicationService:
    Type: AWS::ECS::Service
    DependsOn:
      - ApplicationLoadBalancerHttpListener
      - ApplicationLoadBalancerHttpsListener
    Properties:
      ServiceName: !Sub ${EnvironmentName}-${ServiceName}
      Cluster: !Ref Cluster
      CapacityProviderStrategy:
        - CapacityProvider: FARGATE_SPOT
          Base: 0
          Weight: 1
      PlatformVersion: 1.4.0
      TaskDefinition: !Ref ApplicationTaskDefinition
      DesiredCount: !Ref DesiredCount
      LoadBalancers:
        - ContainerName: nginx
          ContainerPort: 80
          TargetGroupArn: !Ref ApplicationServiceTargetGroup
      HealthCheckGracePeriodSeconds: 60
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref VpcSecurityGroup
          Subnets:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
      EnableExecuteCommand: true
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-${ServiceName}
